# Generated by Django 5.0.2 on 2024-02-10 13:45

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie1',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_type', models.CharField(max_length=75)),
                ('movie_certificate', models.CharField(choices=[('U/A', 'U/A'), ('18+', '18+')], max_length=25)),
                ('language', models.CharField(choices=[('hindi', 'hindi'), ('english', 'english'), ('marathi', 'marathi'), ('south Indian', 'south Indian')], max_length=100)),
                ('duration', models.TimeField(max_length=25)),
                ('director', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='pics')),
            ],
            managers=[
                ('mov', django.db.models.manager.Manager()),
            ],
        ),
    ]
