# Generated by Django 5.0.2 on 2024-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie1',
            name='duration',
            field=models.CharField(max_length=25),
        ),
    ]
