# Generated by Django 5.0.2 on 2024-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_booking_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie1',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
